/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.tictactoe.clientOne;

import javafx.application.Application;

public class Main {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Application.launch(TicTacToeClient.class,args);
    }
}
